name: FARSAND
main: com.farsand.farsand.FSPlugin
version: 1.0
load: startup

commands:
  info:
    description: Info.
    usage: /info
  cleanup:
    description: Cleanup.
    usage: /cleanup
  report:
    description: Report an issue.
    usage: /report
  spawnboats:
    description: Spawns boats?
    usage: /spawnboats
  stackhand:
    description: Stacks hands???
    usage: /stackhand
  row:
    description: row
    usage: /row
  hat:
    description: puts item in hand on head
    usage: /hat