name: FARSAND
main: com.farsand.farsand.FSPlugin
version: 1.0
load: startup

commands:
  info:
    description: Info.
    usage: /info
  cleanup:
    description: Cleanup.
    usage: /cleanup
  report:
    description: Report an issue.
    usage: /report